name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Adjust the branch name if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Get repository name
        id: repo_name
        run: echo "::set-output name=name::$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)"

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=${{ steps.repo_name.outputs.name }}
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${{ github.run_number }} .

      - name: Push Docker image to DockerHub
        run: |
          docker buildx use default
          IMAGE_NAME=${{ steps.repo_name.outputs.name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${{ github.run_number }}

      - name: Login to GitHub Packages Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

      - name: Tag and push Docker image to GitHub Packages
        run: |
          IMAGE_NAME=${{ steps.repo_name.outputs.name }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${{ github.run_number }} docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:${{ github.run_number }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:latest docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:latest
          docker push docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:${{ github.run_number }}
          docker push docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:latest
